### ISSUE TITLE
LICENSE and packaging

### ISSUE THREAD

**Issue by AminRezaei0x443** [anomaly-guard/nft-deployer#2]
Please add a license to the repository. Optionally you can publish `pyfift` in PyPI and update the tutorial accordingly.

**Comment by anomaly-guard** [comment]
Thanks for reminding, added license in https://github.com/anomaly-guard/nft-deployer/commit/5b78d856a5f2d08d6f24cf519253089456685746. I'll do the pypi upload soon too!
