### ISSUE TITLE
privatekey

### ISSUE THREAD

**Issue by eliot58** [anomaly-guard/nft-deployer#6]
How to get a 32 byte private key tonweb is giving 64 bit private key by mnemonic

**Comment by anomaly-guard** [comment]
Use the first 32 bytes, It will have the same behavior.

**Comment by ghost** [comment]
Seems converting mnemonics to a public/private key pair and using the first 64 characters did the trick indeed.

Can I ask how things work here? Is it possible to mint a collection and NFTs to a supported address by Tonkeeper? Tonkeeper supports v3R2, but my address there is completely different from what I got with the private key method.

Can you guide me on this, @anomaly-guard? My goal would be to access these NFTs and collections with standard wallets and wallet connect as well.

**Comment by ghost** [comment]
It needs maybe similar?

https://github.com/anomaly-guard/nft-deployer/blob/main/pyfift/wallet/wallet_v3_r2.py#L23  
  
```
    0 32 u, // seq-no
    698983191 32 u, // subwallet
```

698983191 seems to be the magic number according to some github repo and articles online. seq-no is can be queried from the blockchain wallet contract. If let's say seq-no is 7 according to 

https://testnet.toncenter.com/api/v2/getExtendedAddressInformation?address=%wallet%


Then:
```
    7 32 u, // seq-no
    698983191 32 u, // subwallet
```

Or I'm lost with this. Seems can't get the same generation as generic wallets.
